added kanji program
bunbunjin/practice pull request #1
Opened 2019-11-16 12:17 UTC by bunbunjin

2019-11-16 12:28 UTC, puhitaku requested changes
修正ポイントを上げたので修正をお願いします。

余計な空行など、機械的に修正できることは [black](https://github.com/psf/black) などを使って形式を揃えるのが良いと思います。

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_conversion1.py
> +
2行空いてるので1行にしてください

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_conversion1.py
> +
関数下の空行は不要です、以下同じ

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_conversion1.py
> +    kanji_suu_list = list(kanji_suu)
変数名は極力英単語にしましょう

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_conversion1.py
> +        aaa = kanji[con]
変数名は極力短く、意味のある名前にしましょう

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_conversion1.py
> +    print(accum)
最後の行には改行を入れましょう

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_main.py
> +#ここにファイル
他人に読んでもらえる有益な情報を書き残したほうがいい場合にコメントは使います。余計なコメントは残さないようにしましょう。

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_main.py
> +
空行

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_main.py
> +kanji_jud = kanji_suu.isdigit()
isdigitはUnicodeベースで判定が結構微妙なので、本当に受け入れたい桁の漢字のみを調べたほうが良いかと思います

```
chars = ['一二三四五六七八九十百千']
if any(c not in chars for c in kanji_suu):
    raise ValueError('Unknown kanji was input')
```

2019-11-16 12:28 UTC, puhitaku commented on kanji/kanji_main.py
> +    #print('ここに結果が出る')
コードはコメント化して残さずに、消しましょう。消しても歴史には残るので、後から戻せます。（今回はファイルを追加するコミットだから残らないけど）

2019-11-18 04:54 UTC, puhitaku commented
https://github.com/bunbunjin/practice/pull/1/commits/eeb408628d80ffa1c4379c0cddd0006c9ef25a92
このコミットは一体…

2019-11-18 04:56 UTC, puhitaku commented
修正点をコミットしてプッシュしたら、既にされているコメントに「◯◯のコミットで修正しました」と返信をお願いします。◯◯の部分はコミットハッシュを入れれば自動的にリンクになります。

細かいやつなら単に既読として :+1: とかでもいいです。

2019-11-18 13:06 UTC, bunbunjin commented
上のコミットは訳も分からずしていたら間違えた奴です。

2019-11-22 06:36 UTC, puhitaku commented
このPRの作業はいかがかな？見たところでは進んでいるようだけど

2020-01-03 08:22 UTC, bunbunjin reviewed
up真ん中のやつが間違えたやつ

2020-01-03 08:29 UTC, puhitaku requested changes
あと少し！

2020-01-03 08:29 UTC, puhitaku commented on kanji/test.py
> +        self.assertEqual(convert('一億七万五千八百五十四'), 100075854)
test_convert_okuがダブってるので片方しか実行されないはず。名前を別にしてください。

2020-01-03 08:29 UTC, puhitaku commented on kanji/kanji_conversion.py
> +    print(accum)
この関数は値を計算して返す関数なのでprintしないほうがベターです。

2020-01-03 09:07 UTC, puhitaku approved these changes
![cheers](https://user-images.githubusercontent.com/2425178/71715164-d04b9900-2e53-11ea-8cc8-dcf7734c6077.gif)

2020-01-03 09:07 UTC, merged